apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: xdmod-os-app-cred
  namespace: xdmod
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: xdmod-os-app-cred
  data:
  - secretKey: client_name
    remoteRef:
      key: xdmod/openstack
      property: NAME
  - secretKey: client_id
    remoteRef:
      key: xdmod/openstack
      property: ID
  - secretKey: client_secret
    remoteRef:
      key: xdmod/openstack
      property: SECRET
